exports.signup = async (req, res, next) => {
    try {

    } catch(err){

    }
}

exports.login = async (req, res, next) => {
    try {
        res.json({ message: 'login success'})
    } catch(err){

    }
}

exports.resetPassword = async (req, res, next) => {
    try {
        
    } catch(err){

    }
}